FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc g++ build-essential && rm -rf /var/lib/apt/lists/*

RUN pip install torch --index-url https://download.pytorch.org/whl/cpu

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

RUN python download_models.py

EXPOSE 8081

CMD ["python", "transformer_api.py"]
